name: Arbcore
favicon: null
layout_spectrum: 0.1969411016907543
typography_spectrum: 0.6847062020096928
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.05783949582837522
  lightness: 0.8778871800750494
  saturation: 0.2628221984487027
  rhythmicContrast: 0.8389350294601172
purpose: []
